[project]
site_name = "py-fullstack-template"
# Update these URLs when you deploy your documentation
site_url = "https://example.com/docs"
repo_url = "https://github.com/James-Leslie/py-fullstack-template"
nav = [
    { "Home" = "index.md" },
    { "Guide" = ["guide/getting-started.md", "guide/publishing.md"] },
    { "API Reference" = ["reference/counter.md"] },
]

[project.theme]
features = ["navigation.tabs"]

[project.plugins.mkdocstrings.handlers.python]
paths = ["."]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
show_source = true
merge_init_into_class = true
