[project]
site_name = "py-fullstack-template"
# Update this URL when you deploy your documentation
site_url = "https://example.com/docs"

[project.theme]
features = ["navigation.tabs"]

[project.plugins.mkdocstrings.handlers.python]
paths = ["."]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
show_source = true
